---

- name: Download and install Composer into the current directory.
  shell:
    echo; {{ composer_php_bin }} -r "readfile('https://getcomposer.org/installer');" | {{ composer_php_bin }}
    creates={{ composer_path }}

- name: Move Composer into bin directory.
  shell:
    mv composer.phar {{ composer_path }}
    creates={{ composer_path }}
